"""empty message

Revision ID: 541a07180737
Revises: ebbe7ca376e4
Create Date: 2020-06-26 18:52:16.115831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541a07180737'
down_revision = 'ebbe7ca376e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('done', table_name='todos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('done', 'todos', ['done'], unique=True)
    # ### end Alembic commands ###
